version: '3.7'

services:
  exam_srv:
    image: exam_srv
    container_name: exam_srv
    ports:
      - "8081:8081"
    networks:
      - exam_network

  selenium:
    image: seleniarm/standalone-chromium
    container_name: selenium
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - exam_network

  test_runner:
    image: rustamtest
    container_name: test_runner
    volumes:
      - /Users/qamacos/PycharmProjects/servers_exam/allureresults:/test_dir/allure-results
    networks:
      - exam_network
    depends_on:
      - exam_srv
      - selenium
    environment:
      - BASE_URL_2=http://host.docker.internal:8081
      - REMOTE_BROWSER=http://selenium:4444/wd/hub
      - LOCAL_BROWSER=False

networks:
  exam_network:
    driver: bridge
